# Generated by Django 5.2.4 on 2025-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
