# Generated by Django 5.2.4 on 2025-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(default=-270, max_length=8),
            preserve_default=False,
        ),
    ]
