# Generated by Django 5.2.4 on 2025-08-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_address_order_order_guest_email_and_more'),
    ]

    operations = [
    ]
